Feature/infrastructure
LehailNet/Notation pull request #2
Opened 2022-07-21 22:02 UTC by LehailNet

2022-07-26 19:47 UTC, TomaKuch requested changes

2022-07-26 19:47 UTC, TomaKuch commented on Notation.Domain.Core/obj/Notation.Domain.Core.csproj.nuget.dgspec.json
> +          "dependencies": {
- [ ] Этих файлов не должно быть.  Папки /.vs , /obj и их содержимое - убрать. проверить гит игнор и ветку где он лежит. есть ли в твоей ветке гит игнор.

2022-07-26 19:47 UTC, TomaKuch commented on Notation.Domain.Core/obj/project.assets.json
>  {
убрать файл

2022-07-26 19:47 UTC, TomaKuch commented on Notation.Domain.Core/obj/project.nuget.cache
>  {
убрать

2022-07-26 19:47 UTC, TomaKuch commented on Notation.Infrastructure.Data/MongoDbContext.cs
> +        private MongoClient client;
для чего тебе нужен объект клиента?

2022-07-26 19:47 UTC, TomaKuch commented on Notation.Infrastructure.Data/MongoDbContext.cs
> +        private string _connectionString;
кроме как для открытия коннекта где юзается?
Почему в конструктор передается стринга а не объект конфигурации? если появится больше данных ты их будешь каждую добавлять в консруктор?

2022-07-26 19:47 UTC, TomaKuch commented on Notation.Infrastructure.Data/MongoDbContext.cs
> +        public IMongoDatabase GetMongoDatabase()
- [ ]  IMongoDatabase создавать в конструкторе как минимум. Сделать геттер где возвращать объект.

2022-07-26 19:47 UTC, TomaKuch commented on Notation.Infrastructure.Data/MongoDbContext.cs
> +        private IMongoDatabase database;
- [ ] Сделать свойством

2022-07-26 19:47 UTC, TomaKuch commented on Notation.Infrastructure.Data/MongoDbContext.cs
> +    public class MongoDbContext
не самое подходящее название. Подумай еще

2022-07-26 19:47 UTC, TomaKuch commented on Notation/MainWindow.xaml.cs
> +        private string connetctionString;
для зачем?

2022-07-26 19:47 UTC, TomaKuch commented on Notation/MainWindow.xaml.cs
> +        private MongoDbContext db;
для зачем?

2022-07-26 19:47 UTC, TomaKuch commented on Notation.Infrastructure.Data/Repositories/NoteRepository.cs
> +        private IMongoCollection<Note> GetMongoCollection =>
- [ ] Не там находится. У тебя уровень абстрации тут ниже чем у репозитория. Соответственно данный метод не может находится в репозитории и должен быть в классе на уровень ниже.

- [ ] данный метод должен быть дженериком так как будет меняться только тип

- [ ]  Слишком много раз ты используешь получение коллекции. Ты при инициализации репы получаешь IMongoCollection и дальше работаешь с ней

2022-07-30 14:50 UTC, LehailNet commented on Notation.Infrastructure.Data/MongoDbContext.cs
> +        private MongoClient client;
Перенес создание клиента в метод. Просто изначально у меня был метод создания клиента, поэтому была проверка объекта, а потом я переделал на проверку БД

2022-08-04 20:43 UTC, LehailNet commented on Notation.Infrastructure.Data/MongoDbContext.cs
> +    public class MongoDbContext
Сократил просто до MongoContext)

2022-08-04 20:43 UTC, LehailNet commented on Notation/MainWindow.xaml.cs
> +        private string connetctionString;
для говно кода?)

2022-08-07 12:42 UTC, TomaKuch requested changes

2022-08-07 12:42 UTC, TomaKuch commented on Notation.Infrastructure.Data/AppSettings.cs
> +        public static string ConnectionString { get; set; }
connectionstring чего?
название класса не говорит об этом.
какие то абстрактные настройки и непонятная строка

2022-08-07 12:42 UTC, TomaKuch commented on Notation.Infrastructure.Data/MongoContext.cs
> +        AppSettings AppSettings { get; }
модификатор добавить

2022-08-07 12:42 UTC, TomaKuch commented on Notation.Infrastructure.Data/MongoContext.cs
> +            AppSettings = options.Value;
а если кто то провтыкал и не установил настройки или передал null?

2022-08-07 12:42 UTC, TomaKuch commented on Notation.Infrastructure.Data/MongoContext.cs
> +            var connection = new MongoUrlBuilder(AppSettings.ConnectionString);
а для чего создается объект коннекшн ? только чтоб взять имя бд?
в конфииииг!
пора гуглить : https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mongo-app?view=aspnetcore-6.0&tabs=visual-studio

2022-08-07 12:42 UTC, TomaKuch commented on Notation.Infrastructure.Data/Repositories/BaseRepository.cs
> +    public class BaseRepository<T> : IBaseRepository<T> where T : Note
так, а что сдесь делает Note??
он что является базовой сущностью ? - нет
не правильно

2022-08-07 12:42 UTC, TomaKuch commented on Notation/appsettings.json
> +    "ConnectionString": "mongodb://localhost:27017/notation"
Нельзя просто так в апсетинг ложить конекшн стринг. Пока она у тебя одна, а что будет если появится еще какой то коннекшн? будешь именовать connectionString2?

конфигрурации создаются для определенных классов, соответственно у тебя должна быть секция соответсвующая классу, в которой уже складываются данные.

к примеру MongoDb  секция в которой уже лежит connectionString.

2022-08-07 18:41 UTC, merged